# SPDX-License-Identifier: GPL-2.0
subdir-ccflags-y := $(call cc-disable-warning, unused-but-set-variable)
subdir-ccflags-y += -I$(srctree)/drivers/misc/tecno/include

obj-$(CONFIG_TECNO_KI7) += treedumper/
